### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Danehy** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic#1]
请问，字体文件P1里有些字体的粗细不同，那些细体字是因为还没有适配的缘故吗？https://s1.ax1x.com/2022/06/24/jFw7Of.png

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hulenkius** [comment]
您好，感谢关注本项目！

字体文件P1包含的字符量非常多，完全统一风格还需要较长的一段时间。目前我们正在“中日韩统一表意文字扩展C区”的字符，图中所示的是“扩F”区的字符，尚未完全填饱。

如果您对某些字符有急切的使用需求，我们可以提前为您做好您需要的字符。

**Comment by Danehy** [comment]
> 您好，感谢关注本项目！
> 
> 字体文件P1包含的字符量非常多，完全统一风格还需要较长的一段时间。目前我们正在逐步填充“中日韩统一表意文字扩展C区”的字符，图中所示的是“扩F”区的字符，尚未完全填饱。
> 
> 如果您对某些字符有急切的使用需求，我们可以提前为您做好您需要的字符。

不用不用，我只是询问一下。感谢您的回复！请按照你们的步调来吧，我不急着使用！辛苦！
