### ISSUE TITLE
字體包含了部分 Emoji 字符，略微影響使用。

### ISSUE THREAD

**Issue by ososoio** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic#10]
你好！首先感謝作者的創作。

因爲系統 Emoji 字體通常放在 font-family 的最後作爲回退，例如：
~~~css
body {
    font-family: "Source Han Sans K", "Plangothic P1", "Plangothic P2", sans-serif, "Apple Color Emoji";
}
~~~
如果前面的字體搶先顯示部分 Emoji，就會導致這部分 Emoji 顯示得跟系統不一致，影響美感。

所以，我希望本字體後續能剔除掉 Emoji 字符。
我測試了一下，本字體包含了以下 14 個 Emoji 字符：

U+265F  { ♟ }
U+1F7F0  { 🟰 }
U+1F7E0  { 🟠 }
U+1F7E1  { 🟡 }
U+1F7E2  { 🟢 }
U+1F7E3  { 🟣 }
U+1F7E4  { 🟤 }
U+1F7E5  { 🟥 }
U+1F7E7  { 🟧 }
U+1F7E8  { 🟨 }
U+1F7E9  { 🟩 }
U+1F7E6  { 🟦 }
U+1F7EA  { 🟪 }
U+1F7EB  { 🟫 }

可能有疏漏。

最後，祝作者和各位同仁新年快樂！

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
* 从U+1F7E0至U+1F7EB已经删除，下一版本会跟进，因为这些字符是以前用于特殊用途而添加进去的，现在已经不需要了。
* 鉴于U+1F7F0是于Unicode 14.0新添加的字符，很多终端仍然不支持这个字符的显示，因此这个字符如果贸然删除会产生一些其他问题，因此该字符是否能够删除还需进一步讨论。
* U+265F是与其他11个国际象棋进行配套使用的，并且基于思源黑体进行过二次更改，有其他方面的特殊用途，无法单独删除。

如仍有关于这方面的问题，您可尝试将这些字符删除后自用，或将emoji字体的fallback顺序提前。

感谢为本项目提出意见，也祝君新年快乐。
