### ISSUE TITLE
扩展H错位

### ISSUE THREAD

**Issue by Mjzsl123-github** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic#4]
扩展H与 https://www.unicode.org/charts/PDF/Unicode-15.0/U150-31350.pdf 和 yedict.com 上的数据不符合
例如：U+31473的字型应该是 ⿱又主 而不是 ⿰𠂤又 （31474的字型）

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Hulenkius** [comment]
感谢关注本项目。扩展 H 区在其制定过程中屡次更改字形和码位，目前本项目的扩展 H 区处于初步完成阶段，未对字形进行精校，不能正式投入使用。请期待后续版本。

**Comment by Mjzsl123-github** [comment]
也是。如果 ⿰金西 和 U+2B496 认同了编码又要变
