### ISSUE TITLE
「𣣍」的字形是否正确？

### ISSUE THREAD

**Issue by Mjzsl123-github** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic#9]
此字为左右结构。字体中好像是包围结构
左边的「虎」部件貌似也不符合码表里G源的字形。

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
> 此字为左右结构。字体中好像是包围结构 左边的「虎」部件貌似也不符合码表里G源的字形。

是的，此字的字形不正确，下一个版本会对该字进行更正。
